### ISSUE TITLE
knex migrate:latest fails in PROD

### ISSUE THREAD

**Issue by natekonimbo** [Midburn/spark#230]
This is the output after running `knex migrate:latest` for release v2.0.0

```sh
Working directory changed to /opt/spark/latest
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
Using environment: production
Knex:warning - migrations failed with error: create table `vol_departments` (`id` int unsigned not null auto_increment primary key, `name_en` varchar(255), `name_he` varchar(255)) default character set utf8 - ER_TABLE_EXISTS_ERROR: Table 'vol_departments' already exists
Error: ER_TABLE_EXISTS_ERROR: Table 'vol_departments' already exists
    at Query.Sequence._packetToError (/opt/spark/latest/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/opt/spark/latest/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/opt/spark/latest/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/opt/spark/latest/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/opt/spark/latest/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/spark/latest/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
    --------------------
    at Protocol._enqueue (/opt/spark/latest/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/opt/spark/latest/node_modules/mysql/lib/Connection.js:208:25)
    at /opt/spark/latest/node_modules/knex/lib/dialects/mysql/index.js:124:18
    at Promise._execute (/opt/spark/latest/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/opt/spark/latest/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/opt/spark/latest/node_modules/bluebird/js/release/promise.js:79:10)
    at Client._query (/opt/spark/latest/node_modules/knex/lib/dialects/mysql/index.js:118:12)
    at Client.query (/opt/spark/latest/node_modules/knex/lib/client.js:187:24)
    at /opt/spark/latest/node_modules/knex/lib/transaction.js:247:21
    at tryCatcher (/opt/spark/latest/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/spark/latest/node_modules/bluebird/js/release/method.js:39:29)
    at Client.trxClient.query (/opt/spark/latest/node_modules/knex/lib/transaction.js:244:39)
    at Runner.<anonymous> (/opt/spark/latest/node_modules/knex/lib/runner.js:129:36)
    at Runner.tryCatcher (/opt/spark/latest/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/opt/spark/latest/node_modules/bluebird/js/release/method.js:15:34)
    at Runner.queryArray (/opt/spark/latest/node_modules/knex/lib/runner.js:174:40)
    at /opt/spark/latest/node_modules/knex/lib/runner.js:53:23
    at tryCatcher (/opt/spark/latest/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/spark/latest/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/opt/spark/latest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/spark/latest/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/spark/latest/node_modules/bluebird/js/release/promise.js:569:18)
```

**Comment by asihud** [comment]
it seems there is an issue in the volenteers.
how are we going to fix that, I guess this also make a problem on getting the Spark online ?

**Comment by ArtyomKa** [comment]
I'm not sure how it happens, but it looks like the [volunteers tables migration](https://github.com/Midburn/Spark/blob/master/migrations/20170303180503_volunteers.js) is executed twice. This should not happen, since there should be _knex_migrations_ table in the DB (at least in sqlite there is).
Can someone verify it?

If this is the case, maybe changing the table creation statement to a conditional one will fix this, or dropping the table (it should be empty anyway).

**Comment by OriHoch** [comment]
migrations framework works on production (or at least worked until a few weeks ago)

common problems which might cause such problems - 
* name of the migration was modified (e.g. - the table was created when migration was called X, then someone renamed the migration filename to Y - and now knex tries to run it again)
* someone added the table manually in DB - without going through knex

to fix it you need to ensure the state of DB as knex knows it - is the same as it really is. Knex knows the state of DB by tracking name of migration files which ran.

Usually it means to manually modify the DB to match state which knex expects, in this case, it means to delete volunteers table in DB (but worth to investigate why it happened to prevent it in the future)

**Comment by ArtyomKa** [comment]
Who has access to prod DB?

**Comment by natekonimbo** [comment]
I do have access.

Knex migration table looks like this:
```
|  1 | 20161208025453_init.js                                                          |     1 | 2017-02-08 06:58:03 |
|  2 | 20170112190330_camps.js                                                         |     1 | 2017-02-08 06:58:03 |
|  3 | 20170113114610_constraints.js                                                   |     1 | 2017-02-08 06:58:03 |
|  4 | 20170117090129_drupal_users.js                                                  |     1 | 2017-02-08 06:58:03 |
|  5 | 20170130120027_camps_add_accept_families_facebook_page_url_contact_person_id.js 
```

and tables in DB are:
```
| Tables_in_spark       |
+-----------------------+
| camp_details          |
| camps                 |
| drupal_users          |
| knex_migrations       |
| knex_migrations_lock  |
| npo_members           |
| payments              |
| sessions              |
| users                 |
| vol_departments       |
| vol_departments_roles |
| vol_schedule          |
| vol_shifts            |
| vol_types_in_shift    |
| volunteers     
```

**Comment by asihud** [comment]
as suggested, to copy spark db to spark1 , and do clean init

**Comment by natekonimbo** [comment]
Solved.
