### ISSUE TITLE
production shouldn't raise errors about missing session table

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#251]
@asihud did deployment and migration of [v2.1.0](https://github.com/Midburn/Spark/releases/tag/v2.1.0)

(not sure exactly what he did)

now, there is error in the spark web-app about missing session table:
`ER_NO_SUCH_TABLE: Table 'spark.sessions' doesn't exist`

full log:
```
Apr  7 12:57:34 localhost start.sh[21682]: er.query (/opt/spark/latest/node_modules/bluebird/js/release/method.js:15:34)\n    at /opt/spark/latest/node_modules/knex/lib/runner.js:55:21\n    at tryCatcher (/opt/spark/latest/node_modules/bluebird/js/release/util.js:16:23)\n    at /opt/spark/latest/node_modules/bluebird/js/release/using.js:185:26\n    at tryCatcher (/opt/spark/latest/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/opt/spark/latest/node_modules/bluebird/js/release/promise.js:512:31)","code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","index":0}}
Apr  7 12:58:34 localhost start.sh[21682]: 07/04/17 12:58:34.822 ERROR app.js : Possibly Unhandled Rejection at: Promise
Apr  7 12:58:34 localhost start.sh[21682]: #011{"isFulfilled":false,"isRejected":true,"rejectionReason":{"message":"delete from `sessions` where expired < CAST('2017-04-07 12:58:34' as DATETIME) - ER_NO_SUCH_TABLE: Table 'spark.sessions' doesn't exist","stack":"Error: ER_NO_SUCH_TABLE: Table 'spark.sessions' doesn't exist\n    at Query.Sequence._packetToError (/opt/spark/latest/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Query.ErrorPacket (/opt/spark/latest/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)\n    at Protocol._parsePacket (/opt/spark/latest/node_modules/mysql/lib/protocol/Protocol.js:280:23)\n    at Parser.write (/opt/spark/latest/node_modules/mysql/lib/protocol/Parser.js:75:12)\n    at Protocol.write (/opt/spark/latest/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/opt/spark/latest/node_modules/mysql/lib/Connection.js:103:28)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:551:20)\n    --------------------\n    at Protocol._enqueue (/opt/spark/latest/node_modules/mysql/lib/protocol/Protocol.js:141:48)\n    at Connection.query (/opt/spark/latest/node_modules/mysql/lib/Connection.js:208:25)\n    at /opt/spark/latest/node_modules/knex/lib/dialects/mysql/index.js:124:18\n    at Promise._execute (/opt/spark/latest/node_modules/bluebird/js/release/debuggability.js:300:9)\n    at Promise._resolveFromExecutor (/opt/spark/latest/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/opt/spark/latest/node_modules/bluebird/js/release/promise.js:79:10)\n    at Client._query (/opt/spark/latest/node_modules/knex/lib/dialects/mysql/index.js:118:12)\n    at Client.query (/opt/spark/latest/node_modules/knex/lib/client.js:187:24)\n    at Runner.<anonymous> (/opt/spark/latest/node_modules/knex/lib/runner.js:129:36)\n    at Runner.tryCatcher (/opt/spark/latest/node_modules/bluebird/js/release/util.js:16:23)\n    at Runn
```

**Comment by OriHoch** [comment]
this is in the spark deploy log `/var/log/spark-deploy.log`

```
Knex:warning - migrations failed with error: create table `camps` (`created_at` datetime, `updated_at` datetime, `id` int unsigned not null auto_increment primary key, `event_id` varchar(15), `__prototype` enum('theme_camp', 'art_exhibit'), `camp_name_he` varchar(50), `camp_name_en` varchar(50), `camp_desc_he` mediumtext, `camp_desc_en` mediumtext, `type` varchar(100), `status` enum('deleted', 'open', 'closed', 'inactive'), `web_published` boolean default '0', `camp_activity_time` varchar(100), `child_friendly` boolean, `noise_level` enum('quiet', 'medium', 'noisy', 'very noisy'), `public_activity_area_sqm` int, `public_activity_area_desc` mediumtext, `support_art` boolean, `location_comments` mediumtext, `camp_location_street` text, `camp_location_street_time` text, `camp_location_area` text, `addinfo_json` mediumtext, `main_contact` int unsigned, `moop_contact` int unsigned, `safety_contact` int unsigned, `contact_person_name` varchar(100), `contact_person_email` varchar(100), `contact_person_phone` varchar(14)) default character set utf8 - ER_TABLE_EXISTS_ERROR: Table 'camps' already exists
Error: ER_TABLE_EXISTS_ERROR: Table 'camps' already exists
    at Query.Sequence._packetToError (/opt/spark/new/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/opt/spark/new/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/opt/spark/new/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/opt/spark/new/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/opt/spark/new/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/spark/new/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
    --------------------
    at Protocol._enqueue (/opt/spark/new/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/opt/spark/new/node_modules/mysql/lib/Connection.js:208:25)
    at /opt/spark/new/node_modules/knex/lib/dialects/mysql/index.js:124:18
    at Promise._execute (/opt/spark/new/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/opt/spark/new/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/opt/spark/new/node_modules/bluebird/js/release/promise.js:79:10)
    at Client._query (/opt/spark/new/node_modules/knex/lib/dialects/mysql/index.js:118:12)
    at Client.query (/opt/spark/new/node_modules/knex/lib/client.js:187:24)
    at /opt/spark/new/node_modules/knex/lib/transaction.js:247:21
    at tryCatcher (/opt/spark/new/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/spark/new/node_modules/bluebird/js/release/method.js:39:29)
    at Client.trxClient.query (/opt/spark/new/node_modules/knex/lib/transaction.js:244:39)
    at Runner.<anonymous> (/opt/spark/new/node_modules/knex/lib/runner.js:129:36)
    at Runner.tryCatcher (/opt/spark/new/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/opt/spark/new/node_modules/bluebird/js/release/method.js:15:34)
    at Runner.<anonymous> (/opt/spark/new/node_modules/knex/lib/runner.js:175:19)
```

**Comment by OriHoch** [comment]
seems the root of the problem is that migrations ran on a new DB but which had some pre-existing tables

**Comment by OriHoch** [comment]
@asihud  - I'm not sure how to continue, I can fix the bug by clearing the DB and starting knex again - it should work
also, I think it's better to test the process you did locally before doing it on production - I don't see any special problem that won't be reproduced when tested locally

**Comment by OriHoch** [comment]
talked to @natekonimbo  - I'll drop DB and create from scratch again

**Comment by OriHoch** [comment]
```
mysql --host=the.spark.production.secret.database.host --user=spark -p

drop database spark;
create database spark;
ALTER DATABASE spark CHARACTER SET utf8;
ALTER DATABASE spark COLLATE utf8_general_ci;

cd /opt/spark
source .env
cd latest
./knex migrate:latest
```

**Comment by OriHoch** [comment]
production is back!
