### ISSUE TITLE
[Task] investigate error when running migrations on spark production

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#330]
### reproduction steps
* ssh to spark production instance
* `cd /opt/spark/latest`
* `./knex migrate:latest`

#### expected
* no migrations run / no errors

#### actual
```bash
$ ./knex migrate:latest
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
Using environment: production
Knex:warning - migrations failed with error: drop table `volunteers_delete` - ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails
Error: ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails
    at Query.Sequence._packetToError (/opt/spark/latest/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/opt/spark/latest/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/opt/spark/latest/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/opt/spark/latest/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/opt/spark/latest/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/spark/latest/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
    --------------------
    at Protocol._enqueue (/opt/spark/latest/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/opt/spark/latest/node_modules/mysql/lib/Connection.js:208:25)
    at /opt/spark/latest/node_modules/knex/lib/dialects/mysql/index.js:124:18
    at Promise._execute (/opt/spark/latest/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/opt/spark/latest/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/opt/spark/latest/node_modules/bluebird/js/release/promise.js:79:10)
    at Client._query (/opt/spark/latest/node_modules/knex/lib/dialects/mysql/index.js:118:12)
    at Client.query (/opt/spark/latest/node_modules/knex/lib/client.js:187:24)
    at /opt/spark/latest/node_modules/knex/lib/transaction.js:247:21
    at tryCatcher (/opt/spark/latest/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/spark/latest/node_modules/bluebird/js/release/method.js:39:29)
    at Client.trxClient.query (/opt/spark/latest/node_modules/knex/lib/transaction.js:244:39)
    at Runner.<anonymous> (/opt/spark/latest/node_modules/knex/lib/runner.js:129:36)
    at Runner.tryCatcher (/opt/spark/latest/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/opt/spark/latest/node_modules/bluebird/js/release/method.js:15:34)
    at Runner.queryArray (/opt/spark/latest/node_modules/knex/lib/runner.js:174:40)
```

**Comment by ArtyomKa** [comment]
I also see these when running migration on local mysql server. Looks like mysqlserver and sqlite behave somewhat differently, especially regarding foreign keys, and _knex_ lets you find out about this the hardway... Another problem is that travis runs migrations only on sqlite, so the we have bad migrations leaking into the master branch. Opened another issue on that #332

**Comment by ArtyomKa** [comment]
@OriHoch @amotenko @LeonFedotov 
This is what i think happened:
at first, volunteers table was created with compound primary key on `user_id`, `deparment_id` and `event_id`.
after the initial migration was merged and deployed to staging. I decided to create an id column that will be a PK and the combination of the three columns should be unique. But sqllite wouldn't let me drop compound PK. so I decided to rename the table create a new one with the correct key and then delete the old one. This work great in sqlite, but on mysqlserver renaming the table also updated the foreign keys in the table `vol_schedule`
The only solution *I* can think of is deleting all volunteers related solutions and creating them from scratch. There is a pending issue #303 that needs to be done. I think this approach will solve bosth issues.
 What do you guys think?

**Comment by OriHoch** [comment]
the migrations fail on the last line of this migration - 
https://github.com/Midburn/Spark/blob/master/migrations/20170308194741_recreate_volunteers_table.js#L29

seem to me if you just remove that line everything should work properly..

however, it seems some very wierd things are happening with migrations, I think people are not using them correctly, for example, I don't understand how the tables in [the camps_relation migration](https://github.com/Midburn/Spark/blob/master/migrations/20170314192218_camps_relation_db.js) were created - if volunteers migration failed, it would not have run

I assume someone created the tables manually, without the migrations system

this is very problematic.. need to check what's going on with how people are using the system, who does SSH where, etc.. looks like wild west at the moment - @amotenko

**Comment by ArtyomKa** [comment]
@OriHoch 
I tried removing the suggested line, other problems appear.

I also tried executing the sql statement that knex generates directly in mysql console, got error num. 1215. From reading about it a little on SO appears that foreign key can only be defined on indexed columns. Right now Looks like the best solution is to comment out all foreign keys declarations drop all volunteers table shift and schedule tables that are no longer required (using migrations of course) and recreate the volunteers with only the required FKs

**Comment by OriHoch** [comment]
I think the other problems are due to camp members migration

your plan sounds good

another option - reset migrations

**Comment by asihud** [comment]
I myself executed the migration on production, once created the production databases, and imported all the camps data.
We had some issues with migration then (also because of foreign key, that mysql cannot use foreign key for unsigned fields or signed field. can't remember, but it is github documented),
but eventually everything worked flawless. 
@OriHoch suggestion that something done manually is wrong.
(if the volunteers tables was crashing during migration, the camps_members will not be created) 
At the moment i cannot ssh to production, so I cannot find out what is the exact time, this process was done (to see what was the migration files state at that moment)

on staging server i have created a script /opt/spark/create-db.sh
this script remove the db, and execute all migration, and import the camps data into db.
its a good place to start. 

I do not know what you want to do, but you should extra carefull, 
as production db is running production, and it is very important to harm the data.

**Comment by ArtyomKa** [comment]
I have a theory on how the camps migrations where executed before the volunteers:
* Both where created on different branches.
* Volunteers migration was created before the camps
* Camps where merged into the master and executed on  the server before the volunteers migration was merged.

Yes. having smaller PR and shorter living feature branches would have solved that.

**Comment by OriHoch** [comment]
https://github.com/Midburn/Spark/pull/333

**Comment by roy-zahor** [comment]
https://github.com/Midburn/Spark/pull/338 might solve this issue.

**Comment by OriHoch** [comment]
this issue is about investigating why it happened, I think we know now :+1:
