### ISSUE TITLE
production spark: login hangs for user which didn't complete drupal profile update

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#549]
## reproduction
* have user which didn't add details of emergency contact as required in drupal profile
* try to log-in to production spark https://spark.midburn.org/

### expected
* log-in

### actual
* stuck
* server logs contain error which I assume is due to unhandled error from drupal:
```
spark | 2018-01-06T13:03:03.105855160Z | at process._tickDomainCallback (internal/process/next_tick.js:228:7) }
-- | -- | --
spark | 2018-01-06T13:03:03.105848004Z | at <anonymous>
spark | 2018-01-06T13:03:03.105810895Z | at /home/spark/libs/passport.js:68:55
spark | 2018-01-06T13:03:03.105803387Z | <rejected> TypeError: Cannot read property 'uid' of undefined
spark | 2018-01-06T13:03:03.105743339Z | 06/01/18 01:03:03.105 ERROR app.js : Possibly Unhandled Rejection at: Promise Promise {


```

**Comment by OriHoch** [comment]
fixed in #577 
UX improvements issue - #578
