### ISSUE TITLE
review production error log

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#651]
searching for "ERROR" on production spark pod produces many errors

it's possible some of these are not errors, in which case, worth to consider to reduce to warning

you can see the logs on google console (Ask for view permissions if you don't have)

I found the following main error types (replaced private details with `*****`):

```
spark | Feb 22, 2018, 10:30:01 AM | at Response.toError (/home/spark/node_modules/superagent/lib/node/response.js:94:15)
-- | -- | --
spark | Feb 22, 2018, 10:30:01 AM | { Error: cannot GET /en/api/usersearch?mail=*****%40gmail.com (403)
spark | Feb 22, 2018, 10:30:01 AM | error:
spark | Feb 22, 2018, 10:30:01 AM | serverError: false,
spark | Feb 22, 2018, 10:30:01 AM | clientError: true,
spark | Feb 22, 2018, 10:30:01 AM | 22/02/18 08:30:01.536 ERROR libs/drupal_access.js : { Error: Forbidden
spark | Feb 22, 2018, 10:30:01 AM | at Response.toError (/home/spark/node_modules/superagent/lib/node/response.js:94:15)
spark | Feb 22, 2018, 10:30:01 AM | { Error: cannot GET /en/api/usersearch?mail=********%40gmail.com (403)
```

```
spark | Feb 22, 2018, 10:30:03 AM | at Response.toError (/home/spark/node_modules/superagent/lib/node/response.js:94:15)
-- | -- | --
spark | Feb 22, 2018, 10:30:03 AM | { Error: cannot GET /en/api/usersearch?mail=********%40gmail.com (403)
spark | Feb 22, 2018, 10:30:03 AM | error:
spark | Feb 22, 2018, 10:30:03 AM | serverError: false,
spark | Feb 22, 2018, 10:30:03 AM | clientError: true,
spark | Feb 22, 2018, 10:30:03 AM | 22/02/18 08:30:03.302 ERROR libs/drupal_access.js : { Error: Forbidden
```

```
spark | Feb 22, 2018, 10:30:11 AM | {"message":"********:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:\n","stack":"Error: ********:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:\n","stage":"init"}
-- | -- | --
spark | Feb 22, 2018, 10:30:11 AM | 22/02/18 08:30:11.350 ERROR libs/mail.js : Error sending email
```

```
spark | Feb 22, 2018, 10:30:23 AM | {"message":"********:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:\n","stack":"Error: ********:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:\n","stage":"init"}
-- | -- | --
spark | Feb 22, 2018, 10:30:23 AM | 22/02/18 08:30:23.962 ERROR libs/mail.js : Error sending email
```

```
spark | Feb 22, 2018, 10:31:04 AM | {"message":"********:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:\n","stack":"Error: ********:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:\n","stage":"init"}
-- | -- | --
spark | Feb 22, 2018, 10:31:04 AM | 22/02/18 08:31:04.771 ERROR libs/mail.js : Error sending email
spark | Feb 22, 2018, 10:30:30 AM | <rejected> TypeError: Cannot read property 'uid' of undefined
spark | Feb 22, 2018, 10:30:30 AM | 22/02/18 08:30:30.588 ERROR app.js : Possibly Unhandled Rejection at: Promise Promise {
spark | Feb 22, 2018, 10:30:27 AM | <rejected> TypeError: Cannot read property 'uid' of undefined
spark | Feb 22, 2018, 10:30:27 AM | 22/02/18 08:30:27.769 ERROR app.js : Possibly Unhandled Rejection at: Promise Promise {
```

**Comment by ArtyomKa** [comment]
Are there many entries like this, or is just that one? We call drupal search api as part of handling volunteers  module api calls. I don't know how SSL is connected to that.

**Comment by OriHoch** [comment]
there are a lot of errors, every few minutes

**Comment by ArtyomKa** [comment]
Maybe drupal is having load issues?

**Comment by OriHoch** [comment]
makes sense.. also there are user complaints around the login
I think that Google analytics on all projects will be very helpful to debug these sort of things

**Comment by amotenko** [comment]
@OriHoch do we still have those?
